### ISSUE TITLE
`Error parsing lexer`

### ISSUE THREAD

**Issue by ntdb** [stormwarning/jsont-tmbundle#1]
I received this upon installing the package through Package Control and am unable to use the syntax after installation. Sublime Text build 3083.

```
error parsing lexer: Packages/JSON-Template/Syntaxes/JSONT.tmLanguage: Error parsing plist xml: expected > in file Packages/JSON-Template/Syntaxes/JSONT.tmLanguage on line: 146
```

**Comment by stormwarning** [comment]
Thanks for the heads-up @ntdb! I'm not as familiar with the Sublime package as I am with Atom, but I'll try to sort out the error. If it's an easy solution, please open a pull request!

**Comment by stormwarning** [comment]
The new version might fix this; please let me know!
