### ISSUE TITLE
Instalation error on sublime text

### ISSUE THREAD

**Issue by enmanuelr** [stormwarning/jsont-tmbundle#3]
Getting this error when trying to install the package on sublime text via package manager. Using sublime build 3103.

```
error parsing lexer: Packages/JSON-Template/Syntaxes/JSONT.tmLanguage: Error parsing plist xml: expected > in file Packages/JSON-Template/Syntaxes/JSONT.tmLanguage on line: 146
```

**Comment by stormwarning** [comment]
Thanks for pointing out the error. I'm still looking for a fix.

**Comment by stormwarning** [comment]
I've updated the code and added a new release; please let me know if you still get the error.
