### ISSUE TITLE
Not doing anything on ST3

### ISSUE THREAD

**Issue by thetoxicavenger** [stormwarning/jsont-tmbundle#4]
I'm not an expert in ST, so I may just be screwing up, but upon "Install Package" and restarting Sublime, I didn't get any syntax highlighting for JSONT. However, I found out that your Atom package does work, so thanks for introducing me to Atom ;)

**Comment by stormwarning** [comment]
Well you're welcome then! 👍  Hope the Atom package works out for you.

**Comment by thetoxicavenger** [comment]
Thanks dawg. Do you make your own SQS templates? If so, is that something that's worth pursuing? I looked over the documentation for JSON-T @ SQS, and it looks like it's a bit of a learning curve for making your own templates. I ask b/c I would like to learn custom template Dev on at least one of the popular CMS platforms, and really don't like Wordpress - do you have any friendly suggestions?

(By the way, I am aware of the fact that this might not be a proper use of the issues section, but any help would be greatly appreciated ;)

**Comment by stormwarning** [comment]
I love Squarespace, but you may find yourself frustrated by its limitations on the dev platform. If you're not a fan of WordPress, take a look at Wagtail; a Django CMS. It's definitely one to watch.

**Comment by thetoxicavenger** [comment]
Thanks man, I appreciate it!
